POST https://api-test.heerharmog.workers.dev/
Content-Type: application/json

{
  "method": "GET",
  "url": "https://jsonplaceholder.typicode.com/todos/1",
  "headers": {},
  "body": {}
}

###

POST http://ligong.deshineng.com:8082/brmclg/api/logon/login?time=1677759602639
Content-Type: application/json

{
  "code": "20191953",
  "password": "2e4d7672fe3571f59df8448384ec8b29"
}

###
GET http://127.0.0.1:8788/api/user?user=20191953&pwd=800518
Accept: application/json

###

GET https://b1864732.tut-bathroom.pages.dev/api/user?user=20191953&pwd=800518
Content-Type: application/json

