/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HaCard: typeof import('./src/components/ha-card.vue')['default']
    HaDialog: typeof import('./src/components/ha-dialog.vue')['default']
    HaInput: typeof import('./src/components/ha-input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TailButton: typeof import('./src/components/tail-button.vue')['default']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
